esphome:
  name: ${name}
  comment: Everything Presence Lite
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True
  project:
    name: EverythingSmartTechnology.Everything Presence Lite
    version: "1.0.11"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: ${log_level}
  hardware_uart: UART0

# Enable Home Assistant API
api:

ota:
  platform: esphome

http_request:
  verify_ssl: false

wifi:

i2c:
  - id: bus_a
    sda: 21
    scl: 22
    scan: true
  - id: bus_b
    sda: 27
    scl: 26
    scan: true

light:
  - platform: status_led
    name: ESP32 LED
    pin: GPIO14
    internal: False
    restore_mode: ALWAYS_OFF

number:
  - platform: template
    name: "Illuminance Offset"
    id: illuminance_offset_ui
    unit_of_measurement: "lx"
    min_value: -100
    max_value: 100
    step: 5
    mode: slider
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: 0
    icon: "mdi:brightness-5"
    entity_category: config
    on_value:
      - lambda: 'id(illuminance_sensor).update();'

sensor:
  - platform: bh1750
    name: Illuminance
    i2c_id: bus_a
    id: illuminance_sensor
    address: 0x23
    update_interval: ${illuminance_update_interval}
    filters:
      - lambda: "return x + id(illuminance_offset_ui).state;"
      - clamp:
          min_value: 0

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"
